{
  "changed": false,
  "skip_reason": "Conditional result was False",
  "false_condition": "item.0.json.count | default(0) | int > 0",
  "_ansible_no_log": false,
  "item": [
    {
      "content": "",
      "redirected": false,
      "url": "https://netbox.gt-t.net/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163",
      "status": -1,
      "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 1923, in fetch_url\n    r = open_url(url, data=data, headers=headers, method=method,\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 1686, in open_url\n    return Request().open(method, url, data=data, headers=headers, use_proxy=use_proxy,\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 1578, in open\n    r = urllib_request.urlopen(request, None, timeout)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 214, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 517, in open\n    response = self._open(req, data)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 534, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 494, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 605, in https_open\n    return self.do_open(self._build_https_connection, req)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 1346, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers,\n  File \"/usr/lib64/python3.9/http/client.py\", line 1285, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib64/python3.9/http/client.py\", line 1296, in _send_request\n    self.putrequest(method, url, **skips)\n  File \"/usr/lib64/python3.9/http/client.py\", line 1130, in putrequest\n    self._validate_path(url)\n  File \"/usr/lib64/python3.9/http/client.py\", line 1230, in _validate_path\n    raise InvalidURL(f\"URL can't contain control characters. {url!r} \"\nhttp.client.InvalidURL: URL can't contain control characters. '/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163' (found at least ' ')\n",
      "elapsed": 0,
      "changed": false,
      "failed": false,
      "msg": "Status code was -1 and not [200]: An unknown error occurred: URL can't contain control characters. '/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163' (found at least ' ')",
      "invocation": {
        "module_args": {
          "url": "https://netbox.gt-t.net/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163",
          "headers": {
            "Authorization": "Token 518f3d24e8fe36f88faececc8837283c90d75f17",
            "Accept": "application/json"
          },
          "validate_certs": false,
          "return_content": true,
          "status_code": [
            200
          ],
          "force": false,
          "http_agent": "ansible-httpget",
          "use_proxy": true,
          "force_basic_auth": false,
          "use_gssapi": false,
          "body_format": "raw",
          "method": "GET",
          "follow_redirects": "safe",
          "timeout": 30,
          "remote_src": false,
          "unredirected_headers": [],
          "decompress": true,
          "use_netrc": true,
          "unsafe_writes": false,
          "url_username": null,
          "url_password": null,
          "client_cert": null,
          "client_key": null,
          "dest": null,
          "body": null,
          "src": null,
          "creates": null,
          "removes": null,
          "unix_socket": null,
          "ca_path": null,
          "ciphers": null,
          "mode": null,
          "owner": null,
          "group": null,
          "seuser": null,
          "serole": null,
          "selevel": null,
          "setype": null,
          "attributes": null
        }
      },
      "failed_when_result": false,
      "item": {
        "path": "dcim/devices/",
        "role": "478"
      },
      "ansible_loop_var": "item"
    },
    0
  ],
  "ansible_loop_var": "item",
  "_ansible_item_label": [
    {
      "content": "",
      "redirected": false,
      "url": "https://netbox.gt-t.net/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163",
      "status": -1,
      "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 1923, in fetch_url\n    r = open_url(url, data=data, headers=headers, method=method,\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 1686, in open_url\n    return Request().open(method, url, data=data, headers=headers, use_proxy=use_proxy,\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 1578, in open\n    r = urllib_request.urlopen(request, None, timeout)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 214, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 517, in open\n    response = self._open(req, data)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 534, in _open\n    result = self._call_chain(self.handle_open, protocol, protocol +\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 494, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_ansible.legacy.uri_payload_41up_ir8/ansible_ansible.legacy.uri_payload.zip/ansible/module_utils/urls.py\", line 605, in https_open\n    return self.do_open(self._build_https_connection, req)\n  File \"/usr/lib64/python3.9/urllib/request.py\", line 1346, in do_open\n    h.request(req.get_method(), req.selector, req.data, headers,\n  File \"/usr/lib64/python3.9/http/client.py\", line 1285, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib64/python3.9/http/client.py\", line 1296, in _send_request\n    self.putrequest(method, url, **skips)\n  File \"/usr/lib64/python3.9/http/client.py\", line 1130, in putrequest\n    self._validate_path(url)\n  File \"/usr/lib64/python3.9/http/client.py\", line 1230, in _validate_path\n    raise InvalidURL(f\"URL can't contain control characters. {url!r} \"\nhttp.client.InvalidURL: URL can't contain control characters. '/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163' (found at least ' ')\n",
      "elapsed": 0,
      "changed": false,
      "failed": false,
      "msg": "Status code was -1 and not [200]: An unknown error occurred: URL can't contain control characters. '/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163' (found at least ' ')",
      "invocation": {
        "module_args": {
          "url": "https://netbox.gt-t.net/api/ dcim/devices/?role_id=478&cf_cmd_gnid=2498163",
          "headers": {
            "Authorization": "Token 518f3d24e8fe36f88faececc8837283c90d75f17",
            "Accept": "application/json"
          },
          "validate_certs": false,
          "return_content": true,
          "status_code": [
            200
          ],
          "force": false,
          "http_agent": "ansible-httpget",
          "use_proxy": true,
          "force_basic_auth": false,
          "use_gssapi": false,
          "body_format": "raw",
          "method": "GET",
          "follow_redirects": "safe",
          "timeout": 30,
          "remote_src": false,
          "unredirected_headers": [],
          "decompress": true,
          "use_netrc": true,
          "unsafe_writes": false,
          "url_username": null,
          "url_password": null,
          "client_cert": null,
          "client_key": null,
          "dest": null,
          "body": null,
          "src": null,
          "creates": null,
          "removes": null,
          "unix_socket": null,
          "ca_path": null,
          "ciphers": null,
          "mode": null,
          "owner": null,
          "group": null,
          "seuser": null,
          "serole": null,
          "selevel": null,
          "setype": null,
          "attributes": null
        }
      },
      "failed_when_result": false,
      "item": {
        "path": "dcim/devices/",
        "role": "478"
      },
      "ansible_loop_var": "item"
    },
    0
  ]
}
